Мишин Илья. Задача 10. Сумма элементов матрицы.
allnes/pp_2020_autumn_math pull request #3
Opened 2020-10-14 08:01 UTC by Iliamish

2020-10-14 12:16 UTC, allnes commented
Задача 1, 10 - это вариант.

2020-10-15 21:15 UTC, allnes requested changes

2020-10-15 21:15 UTC, allnes commented on .gitignore
> -.idea/
изменять `.gitignore` можно при условии добавления новго исключения

2020-10-15 21:17 UTC, allnes requested changes

2020-10-15 21:17 UTC, allnes commented on modules/task_1/mishin_i_matrix_elem_sum/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Sum) {
количество тестов не соотвествует инструкции

2020-10-15 22:17 UTC, Iliamish commented on .gitignore
> -.idea/
Я добавил .vscode/ , тут проблема в отображении изменений гитом.

2020-10-15 22:19 UTC, allnes commented on .gitignore
> -.idea/
ок

2020-10-15 22:26 UTC, Iliamish commented on modules/task_1/mishin_i_matrix_elem_sum/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Sum) {
Не заметил уточнение по количеству тестов.

2020-10-15 23:05 UTC, allnes approved these changes

2020-10-15 23:05 UTC, merged