Воденеев Михаил. Задача 1. Нахождение максимальных элементов по столбцам матрицы.
allnes/pp_2020_autumn_math pull request #8
Opened 2020-10-20 14:19 UTC by Vodeneev

2020-10-22 20:34 UTC, allnes requested changes

2020-10-22 20:34 UTC, allnes commented on modules/task_1/vodeneev_m_max_in_col_matrix/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Search_Max_50_50) {
количество тестов не соотвествует инструкции

2020-10-22 20:53 UTC, Vodeneev commented on modules/task_1/vodeneev_m_max_in_col_matrix/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Search_Max_50_50) {
Добавил еще один тест, вроде в инструкции не написано нужное количество

2020-10-22 21:21 UTC, Vodeneev commented on modules/task_1/vodeneev_m_max_in_col_matrix/main.cpp
> +TEST(Parallel_Operations_MPI, Test_Search_Max_50_50) {
извиняюсь, написано, просто проглядел. А Вы можете сейчас замёржить, когда трэвис допроверяет, а то вдруг до дедлайна не успею)

2020-10-23 00:17 UTC, allnes approved these changes

2020-10-23 00:17 UTC, merged